spring:
  datasource:
    url: jdbc:postgresql://ip-address-of-your-server:5432/postgres
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
        ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true